INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (1, '客户服务', '帮助 & 联系', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (2, '客户服务', '返回 & 退款', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (3, '客户服务', '在线商店', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (4, '客户服务', '条款 & 条件', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (5, '公司', '可用的服务', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (6, '公司', '最新的文章', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (7, '社交媒体', 'QQ: 2921310632', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (8, '社交媒体', '邮箱: 2921310632@qq.com', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (9, '社交媒体', '电话号码: 18569380564', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (10, '公司', '关于我们', 1);
INSERT INTO `bottompanel` (`bottom_id`, `title`, `content`, `status`) VALUES (11, '社交媒体', 'QQ:6666666', 1);
